### ISSUE TITLE
Initial bug reports

### ISSUE THREAD

**Issue by rayrayweng** [zaptrem/ReLearn-Feedback#2]
### **Bug 1**
Application crashes

**To Reproduce**
1. Go to Recent
2. Click Zoom icon
3. Press Join (text box is empty)
4. Application crashes

**Expected behavior**
I expect an error saying that the link is empty/invalid.

### **Bug 2**
Images cannot be sent in Group chats

**To Reproduce**
1. Go to Groups
2. Go the chat box
3. Click on purple image icon
4. Nothing happens

**Expected behavior**
I expect to see a pop-up taking me to my photos, with the ability to send images over the group chat.

### **Bug 3**
Unable to see transcription after live recording

**To Reproduce**
1. Go to Recent
2. Record audio
3. Click on recorded audio
4. Can only replay recording, with no transcription present

**Expected behavior**
I expect to see the the transcribed text from the audio recording after expanding the recorded audio

### **Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 13.6.1

**Comment by zaptrem** [comment]
All of these should be resolved as of build 31.
